version: '3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${RDS_ENDPOINT}
      WORDPRESS_DB_USER: wpadmin
      WORDPRESS_DB_PASSWORD: YOUR_SECURE_PASSWORD
    ports:
      - "80:80"
